// Generated by CoffeeScript 1.3.3

$(function() {
  $('.tab').last().hide();
  return $('.tab-titles a').on('click', function(e) {
    var id;
    $('.tab').hide();
    e.preventDefault();
    id = $(e.currentTarget).attr('href');
    return $(id).show();
  });
});
